# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Pipar Sool'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/pipar-main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["pipar_sool_dongle prospector_adapter", "pipar_sool_dongle","pipar_sool_left","pipar_sool_right"]'
      modules: '["rasmuskoit/prospector-zmk-module/dev"]'
      custom_config: '["#define MIRYOKU_TIMELESS_HRM\n#define MIRYOKU_KLUDGE_DOUBLETAPBOOT"]'
