# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build all Pipar Sool variants'
on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        alphas:
          - default
          - dvorak
          - qwerty
        custom_config:
          - ["#define MIRYOKU_ALPHAS_COLEMAKDH"]
          - ["#define MIRYOKU_ALPHAS_DVORAK"]
          - ["#define MIRYOKU_ALPHAS_QWERTY"]
        include:
          - alphas: default
            custom_config: ["#define MIRYOKU_ALPHAS_COLEMAKDH"]
          - alphas: dvorak
            custom_config: ["#define MIRYOKU_ALPHAS_DVORAK"]
          - alphas: qwerty
            custom_config: ["#define MIRYOKU_ALPHAS_QWERTY"]
    uses: ./.github/workflows/pipar-main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["pipar_sool_dongle","pipar_sool_left","pipar_sool_right"]'
      alphas: '${{ matrix.alphas }}'
      custom_config: ${{ toJson(matrix.custom_config) }}