# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Pipar Sool with Matrix'
on: workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/pipar-main.yml
    secrets: inherit
    strategy:
      matrix:
        config:
          - custom_config: '["#define MIRYOKU_ALPHAS_DVORAK"]'
            alphas: '["dvorak"]'
          - custom_config: '["#define MIRYOKU_ALPHAS_QWERTY"]'
            alphas: '["qwerty"]'
          - custom_config: '["#define MIRYOKU_ALPHAS_COLEMAK"]'
            alphas: '["colemak"]'
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["pipar_sool_dongle","pipar_sool_left","pipar_sool_right"]'
      custom_config: ${{ matrix.config.custom_config }}
      alphas: ${{ matrix.config.alphas }}